version: "3.8"

services:
  app:
    depends_on:
      - database-auto-midjourney
    env_file:
      - .env

  database-auto-midjourney:
    image: postgres:12
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
