version: '3.8'

services:

  app:
    build:
      context: .
      target: dev
    environment:
      # - DATABASE_NAME=auto-midjourney
      # - DATABASE_USER_NAME=webapp
      # - DATABASE_USER_PASSWORD=webapp-password
      - DATABASE_URL=postgresql://webapp:webapp-password@database:5432/auto-midjourney?schema=public
    volumes:
      - .:/usr/src/app
    ports:
      - "80:3000"
    command: npm run dev

  database:
    environment:
      POSTGRES_DB: auto-midjourney
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: webapp-password
