services:
  app:
    image: node:20-alpine
    depends_on:
      - database-auto-midjourney
    working_dir: /usr/src/app
    user: node:node
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - DATABASE_NAME=auto-midjourney
      - DATABASE_USER_NAME=webapp
      - DATABASE_USER_PASSWORD=webapp-password
      - DATABASE_URL=postgresql://webapp:webapp-password@database-auto-midjourney:5432/auto-midjourney?schema=public
      - JWT_SECRET=token
    env_file:
      - .env
    ports:
      - "80:3000"
      - "5555:5555"
    command: npm run dev

  database-auto-midjourney:
    image: postgres:12
    environment:
      POSTGRES_DB: auto-midjourney
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: webapp-password
    volumes:
      - database-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      ADMINER_DEFAULT_SERVER: database-auto-midjourney

volumes:
  database-data:
