version: '3.8'

services:

  app:
    image: ghcr.io/thomasritaine/auto-midjourney:main
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - image:/home/bun/app/image
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN_NAME}`)"
      - "traefik.http.routers.${APP_NAME}.middlewares=auth-http-auto-midjourney@file"

volumes:
  image:

networks:
  proxy:
    external: true
